version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django-db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - services-network
    expose:
      - 5432

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./srcs/nginx/frontend:/usr/share/nginx/html
    ports:
      - 80:80
    networks: 
      - services-network

  # django:
  #   build: .
  #   restart: always
  #   networks:
  #     - services-network
  #   command: python manage.py runserver
  #   volumes:
  #     - .:/code
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres

networks:
  services-network:
    driver: bridge
