version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - services-network

  nginx:
    build: ./srcs/nginx
    restart: always
    volumes:
      - ./src/nginx:/usr/share/nginx/html
      - ./srcs/backend/staticfiles:/app/backend/staticfiles
      - ./srcs/nginx/frontend:/var/www/html
    ports:
      - 8000:21000
      - 3000:80
    networks: 
      - services-network
    depends_on:
      - django

  django:
    depends_on:
      - postgres
    build: ./srcs/backend
    restart: always
    env_file:
      - .env
    ports:
      - 8000
    # expose:
    #   - 8000:8000
    networks:
      - services-network
    volumes:
      - ./srcs/backend:/app
      - ./srcs/backend/staticfiles:/app/backend/staticfiles

networks:
  services-network:
    driver: bridge
