version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django-db
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - services-network
    ports:
      - 5432:5432
    depends_on:
      - nginx

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - services-network

networks:
  services-network:
    driver: bridge
