version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - services-network

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./srcs/nginx/frontend:/usr/share/nginx/html
    ports:
      - 80:80
    networks: 
      - services-network

  django:
    build: ./srcs/backend
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    # expose:
    #   - 8000:8000
    networks:
      - services-network
    depends_on:
      - postgres
    
networks:
  services-network:
    driver: bridge
